services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: people_counter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=people_counter
      - DB_USER=postgres
      - DB_PASSWORD=1111
    volumes:
      - ./snapshots:/app/snapshots
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  postgres_data:
